"""
Django settings for persona project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

#Este archivo sirve para configurar todo el proyecto

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rws1k1ix3v%#8$md0sp_3viinsv=ao=l+jo!$5i-*_g7c^f82z' #Es para que django ejore la incriptacion de los usuarios

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Es para decirle a nuestra apllicacion si estamos en produccion o en desarrollo (Es para que brinde mas informacion)

ALLOWED_HOSTS = [] #Es para decirle al sistema que direcciones tiene permitido consultar


# Application definition

INSTALLED_APPS = [ #Aqui aparecen las distintas partes o aplicaciones del proyecto
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Abajo se agregan las aplicacones que se crean y nos permite configurarlas
    'applications.Producto',
    'applications.Cliente',
    'applications.Proveedor',
]

MIDDLEWARE = [#Es para decirle a django si va aprocesar determinados datos de alguna forma
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'persona.urls'

TEMPLATES = [ 
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'persona.wsgi.application' #



# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {  #Motor de la base de datos
    'default': {
        'ENGINE': 'django.db.backends.postgresql', #usa base de datos postgres
        'NAME': 'practica1', #Nombre de la base de datos
        'USER': 'matias', #Nombre del usuario de la base de datos
        'PASSWORD': 'codigoX', #Contraseña para acceder a la base de datos
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [ 
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/' #Es para decirle donde van a estar los archivos estaticos o archivos html
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'