# Generated by Django 3.2 on 2022-12-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='productos',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(default=0, verbose_name='Telefono del proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del proveedor'),
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
