# Generated by Django 3.2 on 2022-12-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0002_auto_20221209_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.CharField(max_length=50, verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Mercaderia',
                'verbose_name_plural': 'Mercaderias',
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='productos',
            field=models.ManyToManyField(to='Proveedor.Mercaderia', verbose_name='Productos que ofrece el proveedor'),
        ),
    ]
