# Generated by Django 3.2 on 2022-12-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0004_alter_mercaderia_prod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Provedor', 'verbose_name_plural': 'Provedoors'},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='productos',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuit',
            field=models.IntegerField(default=None, verbose_name='Cuit del proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(verbose_name='Telefono del proveedor'),
        ),
        migrations.DeleteModel(
            name='Mercaderia',
        ),
    ]
