# Generated by Django 3.2 on 2023-01-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0005_auto_20221212_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido del proveedor'),
            preserve_default=False,
        ),
    ]
