# Generated by Django 3.2 on 2022-12-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dni',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50, null=True, verbose_name='Apelldio del cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(default=0, verbose_name='Telefono del cliente'),
        ),
    ]
