# Generated by Django 3.2 on 2022-12-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_auto_20221209_1425'),
        ('Cliente', '0002_auto_20221209_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(default=None, verbose_name='DNI del cliente'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.ManyToManyField(to='Producto.Producto', verbose_name='compra del cliente')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='changuito',
            field=models.ManyToManyField(to='Cliente.Carrito'),
        ),
    ]
