# Generated by Django 3.2 on 2022-12-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_auto_20221209_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='changuito',
            field=models.ManyToManyField(default=None, to='Cliente.Carrito'),
        ),
    ]
