# Generated by Django 3.2 on 2022-12-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0006_alter_cliente_changuito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='changuito',
            field=models.ManyToManyField(to='Cliente.Carrito'),
        ),
    ]
