# Generated by Django 3.2 on 2022-12-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0007_alter_cliente_changuito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='changuito',
            field=models.ManyToManyField(default=None, to='Cliente.Carrito'),
        ),
    ]
