# Generated by Django 3.2 on 2022-12-12 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0008_alter_cliente_changuito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='compra',
            new_name='changuito',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='changuito',
        ),
        migrations.AddField(
            model_name='cliente',
            name='compra',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Cliente.carrito', verbose_name='carrito del cliente'),
        ),
    ]
