# Generated by Django 3.2 on 2022-12-12 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_auto_20221212_2135'),
        ('Cliente', '0009_auto_20221212_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='changuito',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='compra',
        ),
        migrations.AddField(
            model_name='carrito',
            name='carrito',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='carrito',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido del cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(verbose_name='Dni del cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(verbose_name='Telefono del cliente'),
        ),
    ]
