# Generated by Django 3.2 on 2022-12-12 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_auto_20221212_2135'),
        ('Cliente', '0010_auto_20221212_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='carrito',
            field=models.ForeignKey(blank=True, default='No realizo ninguna compra', on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='carrito',
            field=models.ForeignKey(blank=True, default='No realizo ninguna compra', on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
        ),
    ]
