# Generated by Django 3.2 on 2022-12-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0011_auto_20221212_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre completo'),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='carrito',
        ),
        migrations.AddField(
            model_name='cliente',
            name='carrito',
            field=models.ManyToManyField(to='Cliente.Carrito', verbose_name='Compra del cliente'),
        ),
    ]
