# Generated by Django 3.2 on 2022-12-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='marca del producto')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de producto')),
                ('precio', models.IntegerField(verbose_name='Precio del producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.marca', verbose_name='Marca del producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
