# Generated by Django 3.2 on 2022-12-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_auto_20221209_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='capacidad',
            field=models.FloatField(default=None, verbose_name='Contenido del producto'),
        ),
    ]
