# Generated by Django 3.2 on 2022-12-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0005_auto_20221212_2135'),
        ('Producto', '0003_producto_capacidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='tipo',
            new_name='Tipo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='capacidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(to='Proveedor.Proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0, verbose_name='Existencias disponibles del producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Existencias minimas del producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marca',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='marca del producto'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ManyToManyField(to='Producto.Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(max_length=50, verbose_name='precio de los productos'),
        ),
    ]
