# Generated by Django 3.2 on 2022-12-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0006_alter_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='marca',
            field=models.CharField(default='', max_length=50, verbose_name='marca del producto'),
        ),
    ]
