# Generated by Django 3.2 on 2022-12-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0007_alter_marca_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
    ]
