# Generated by Django 3.2 on 2022-12-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0008_auto_20221226_2143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
